---
- name: Update apt repo and cache
  hosts: k3s_cluster
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 86400
